export default [
  {
    id: 1,
    question: `Find the missing number:
            2, 6, 12, 20, 30, ?`,
    options: ["40", "42", "45"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 2,
    question:
      "A and B together can complete a task in 12 days. B alone can complete it in 20 days. How long will A alone take to complete the task?",
    options: ["15", "30", "25"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 3,
    question:
      "A shopkeeper buys an item for ₹800 and sells it at a profit of 25%. What is the selling price?",
    options: ["₹900", "₹1000", "₹800"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 4,
    question:
      "A bag contains 5 red balls, 3 blue balls, and 2 green balls. If a ball is drawn at random, what is the probability that it is blue?",
    options: ["4/10", "3/10", "5/20"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 5,
    question:
      "A train 120m long crosses a pole in 6 seconds. What is its speed in km/h?",
    options: ["72km", "74km", "75km"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 6,
    question: "If TABLE is coded as UJDNH, how is CHAIR coded?",
    options: ["EJDHT", "DKCKT", "EJDHS"],
    answer: 2,
    testcode: "aptitute",
  },
  {
    id: 7,
    question:
      "If the average marks of 5 students is 75, what is the total sum of their marks?",
    options: ["375", "378", "370"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 8,
    question:
      "Statement: All cats are animals. Some animals are dogs. Conclusion: I. Some cats are dogs. II. All dogs are animals. Which conclusion(s) follow?",
    options: ["Only I", "Only II", "Both I and II"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 9,
    question: "Find the odd one out: Triangle, Square, Rectangle, Circle",
    options: ["Circle", "Square", "Rectangle"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 10,
    question:
      "Pointing to a photograph, Rahul says, 'He is the only son of my mother's father.' How is the man in the photograph related to Rahul?",
    options: ["Father", "GrandFather", "Uncle"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 11,
    question: "What is the next number in the series? 3, 6, 11, 18, 27, ?",
    options: ["36", "38", "40"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 12,
    question:
      "If the price of a book increases by 20% and then decreases by 20%, what is the final price if the initial price was ₹500?",
    options: ["₹500", "₹480", "₹520"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 13,
    question:
      "A train running at 90 km/h crosses a 300m platform in 30 seconds. What is the length of the train?",
    options: ["200m", "250m", "300m"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 14,
    question: "Find the missing term in the sequence: 2, 5, 10, 17, ?, 37.",
    options: ["24", "26", "29"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 15,
    question:
      "A person spends 20% of his income on rent and 30% of the remaining on food. If his income is ₹40,000, how much does he spend on food?",
    options: ["₹9,600", "₹8,400", "₹10,000"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 16,
    question: "If 3x + 4y = 25 and 2x + 5y = 23, find the value of x.",
    options: ["3", "4", "5"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 17,
    question: "If today is Tuesday, what day will it be 100 days from now?",
    options: ["Thursday", "Friday", "Saturday"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 18,
    question:
      "A and B can complete a task in 15 days. B alone takes 25 days. In how many days can A complete the task alone?",
    options: ["40 days", "45 days", "50 days"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 19,
    question:
      "A sum of ₹5000 is invested at 10% simple interest per annum. What will be the total amount after 3 years?",
    options: ["₹6,000", "₹6,500", "₹6,800"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 20,
    question:
      "Pointing to a photograph, Rahul says, 'He is the only son of my mother's father.' How is the man in the photograph related to Rahul?",
    options: ["Father", "GrandFather", "Uncle"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 21,
    question:
      "A man walks 3 km north, then 4 km east. How far is he from the starting point?",
    options: ["5 km", "6 km", "7 km"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 22,
    question: "Find the missing number: 4, 9, 16, 25, ?, 49.",
    options: ["35", "36", "40"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 23,
    question: "Which of the following is the odd one out?",
    options: ["Triangle", "Square", "Pentagon"],
    answer: 2,
    testcode: "aptitute",
  },
  {
    id: 24,
    question:
      "The average of five numbers is 45. If one number is removed, the average becomes 42. What is the removed number?",
    options: ["57", "60", "63"],
    answer: 2,
    testcode: "aptitute",
  },
  {
    id: 25,
    question:
      "In a class of 50 students, 30 like cricket, 25 like football, and 10 like both. How many like neither?",
    options: ["5", "10", "15"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 26,
    question:
      "The sum of two numbers is 70, and their difference is 20. What is the larger number?",
    options: ["45", "50", "55"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 27,
    question:
      "A man saves 20% of his salary. If his salary is ₹50,000, how much does he save?",
    options: ["₹10,000", "₹8,000", "₹12,000"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 28,
    question: "If the perimeter of a square is 48 cm, what is its area?",
    options: ["144 cm²", "196 cm²", "256 cm²"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 29,
    question: "Find the missing number in the sequence: 1, 4, 9, 16, ?, 36.",
    options: ["20", "25", "30"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 30,
    question:
      "What is the probability of getting a head when flipping a fair coin?",
    options: ["1/2", "1/3", "1/4"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 31,
    question:
      "A train of length 120 meters is moving at 54 km/h. How long does it take to cross a pole?",
    options: ["6 sec", "8 sec", "10 sec"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 32,
    question:
      "If A is the brother of B and B is the father of C, how is A related to C?",
    options: ["Uncle", "Father", "Grandfather"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 33,
    question: "If the radius of a circle is doubled, how does the area change?",
    options: ["Doubles", "Triples", "Quadruples"],
    answer: 2,
    testcode: "aptitute",
  },
  {
    id: 34,
    question:
      "A can complete a task in 20 days, B in 30 days. Working together, how many days will they take?",
    options: ["10", "12", "15"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 35,
    question: "What is the smallest prime number?",
    options: ["1", "2", "3"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 36,
    question:
      "If 5 workers can complete a job in 20 days, how long will it take 10 workers?",
    options: ["10 days", "15 days", "5 days"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 37,
    question:
      "A train passes a 150m long platform in 15 seconds. If its speed is 72 km/h, what is the length of the train?",
    options: ["100m", "120m", "150m"],
    answer: 2,
    testcode: "aptitute",
  },
  {
    id: 38,
    question:
      "A number is doubled and then increased by 10. If the result is 50, what was the original number?",
    options: ["15", "20", "25"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 39,
    question: "What is the next number in the pattern: 2, 6, 12, 20, ?",
    options: ["30", "28", "32"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 40,
    question: "A car covers 300 km in 5 hours. What is its speed?",
    options: ["50 km/h", "60 km/h", "70 km/h"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 41,
    question:
      "A shopkeeper gives a 10% discount on an item costing ₹500. What is the final price?",
    options: ["₹450", "₹460", "₹470"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 42,
    question: "Find the missing term: 3, 8, 15, 24, ?, 48.",
    options: ["30", "35", "40"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 43,
    question:
      "If a box contains 5 red and 3 blue balls, what is the probability of drawing a red ball?",
    options: ["5/8", "3/8", "1/2"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 44,
    question:
      "A father is twice as old as his son. In 10 years, the sum of their ages will be 90. What is the son's current age?",
    options: ["20", "25", "30"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 45,
    question: "The sum of the first 10 natural numbers is:",
    options: ["55", "60", "65"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 46,
    question:
      "If a clock is 15 minutes fast, what will be the actual time when it shows 3:45 PM?",
    options: ["3:15 PM", "3:30 PM", "3:00 PM"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 47,
    question:
      "A person walks 5 km east, then 3 km north. How far is he from the starting point?",
    options: ["4 km", "5 km", "6 km"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 48,
    question:
      "A library has 200 books, out of which 40% are fiction. How many fiction books are there?",
    options: ["80", "100", "120"],
    answer: 0,
    testcode: "aptitute",
  },
  {
    id: 49,
    question:
      "A basket contains 20 apples, and 5 are rotten. What fraction are good?",
    options: ["1/2", "3/4", "1/4"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 50,
    question: "If 40% of a number is 80, what is the number?",
    options: ["150", "200", "250"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 51,
    question: "What is the sum of the angles in a quadrilateral?",
    options: ["180°", "360°", "270°"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 52,
    question:
      "A boat travels 30 km downstream in 3 hours. What is the speed of the boat in still water if the current's speed is 2 km/h?",
    options: ["8 km/h", "10 km/h", "12 km/h"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 53,
    question: "What is the least number divisible by both 12 and 18?",
    options: ["24", "36", "48"],
    answer: 1,
    testcode: "aptitute",
  },
  {
    id: 54,
    question:
      "Which of the following best demonstrates time management skills?",
    options: [
      "Working without a break until burnout",
      "Planning tasks with deadlines and prioritizing",
      "Multitasking everything at once without order",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 55,
    question: "How should you handle a disagreement with a team member?",
    options: [
      "Raise your voice to prove your point",
      "Ignore the issue and avoid the person",
      "Discuss respectfully and find a common solution",
    ],
    answer: 2,
    testcode: "softskills",
  },
  {
    id: 56,
    question: "Which of these is an example of a verbal communication skill?",
    options: [
      "Maintaining eye contact",
      "Clearly articulating your thoughts during meetings",
      "Listening without interrupting",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 57,
    question: "What does the phrase 'think on your feet' mean?",
    options: [
      "Go for a walk while thinking",
      "Respond quickly and effectively in unexpected situations",
      "Stand up while answering questions",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 58,
    question: "Choose the correct sentence:",
    options: [
      "Each of the students have a book.",
      "Each of the students has a book.",
      "Each students has a book.",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 59,
    question: "Identify the correctly punctuated sentence.",
    options: ["Lets eat Grandma!", "Let’s eat, Grandma!", "Lets, eat Grandma!"],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 60,
    question: "What is the synonym of the word 'meticulous'?",
    options: ["Careless", "Thorough", "Lazy"],
    answer: 1,
    testcode: "softskills",
  },

  {
    id: 61,
    question: "What is the key to effective communication?",
    options: ["Speaking loudly", "Listening actively", "Using complex words"],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 62,
    question: "Which of the following is a sign of good teamwork?",
    options: [
      "Blaming others for mistakes",
      "Collaborating and supporting team members",
      "Ignoring feedback",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 63,
    question: "What is an essential aspect of problem-solving?",
    options: [
      "Ignoring the problem",
      "Analyzing the situation and finding solutions",
      "Waiting for someone else to solve it",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 64,
    question: "Which of these is an example of emotional intelligence?",
    options: [
      "Recognizing and managing your emotions effectively",
      "Suppressing emotions completely",
      "Avoiding emotional discussions",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 65,
    question: "What is the best way to handle constructive criticism?",
    options: [
      "Ignore it",
      "Take it personally",
      "Accept it and use it for improvement",
    ],
    answer: 2,
    testcode: "softskills",
  },
  {
    id: 66,
    question: "What is a key component of adaptability?",
    options: [
      "Resisting change",
      "Embracing new challenges and learning from them",
      "Sticking to old methods",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 67,
    question: "What is an important factor in time management?",
    options: [
      "Procrastination",
      "Prioritizing tasks effectively",
      "Doing everything at once",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 68,
    question: "Which skill is most important for conflict resolution?",
    options: [
      "Aggression",
      "Active listening and compromise",
      "Avoiding communication",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 69,
    question: "Which of these is NOT a leadership quality?",
    options: [
      "Inspiring others",
      "Taking responsibility",
      "Avoiding accountability",
    ],
    answer: 2,
    testcode: "softskills",
  },
  {
    id: 70,
    question: "How can one demonstrate professionalism at work?",
    options: [
      "Being punctual and respectful",
      "Ignoring deadlines",
      "Gossiping about coworkers",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 71,
    question: "What is the benefit of having a growth mindset?",
    options: [
      "Avoiding challenges",
      "Embracing learning and self-improvement",
      "Sticking to what you know",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 72,
    question: "Which of the following helps in networking?",
    options: [
      "Building relationships and engaging with people",
      "Staying isolated",
      "Avoiding professional events",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 73,
    question: "What is an example of a positive attitude?",
    options: [
      "Finding solutions instead of focusing on problems",
      "Complaining about everything",
      "Blaming others for failures",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 74,
    question: "Which of the following is a key aspect of decision-making?",
    options: [
      "Analyzing facts and making informed choices",
      "Making impulsive choices",
      "Relying solely on emotions",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 75,
    question: "Which of the following helps in stress management?",
    options: [
      "Taking breaks and practicing mindfulness",
      "Avoiding responsibilities",
      "Ignoring problems",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 76,
    question: "Why is active listening important?",
    options: [
      "It helps in understanding and effective communication",
      "It allows ignoring others' opinions",
      "It avoids unnecessary discussions",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 77,
    question: "How can you show initiative at work?",
    options: [
      "Waiting for instructions always",
      "Taking responsibility and suggesting improvements",
      "Doing only the bare minimum",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 78,
    question: "What is a common barrier to effective communication?",
    options: [
      "Active listening",
      "Interrupting and making assumptions",
      "Providing clear messages",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 79,
    question: "Which of the following is a sign of self-confidence?",
    options: [
      "Doubting one's abilities all the time",
      "Believing in one's skills and abilities",
      "Avoiding new challenges",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 80,
    question: "Why is body language important in communication?",
    options: [
      "It conveys emotions and enhances understanding",
      "It is not relevant",
      "It confuses people",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 81,
    question: "What is an example of a positive work ethic?",
    options: [
      "Completing tasks with dedication and responsibility",
      "Leaving work incomplete",
      "Avoiding deadlines",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 82,
    question: "What is the importance of empathy in the workplace?",
    options: [
      "Understanding and relating to others' emotions",
      "Ignoring coworkers' feelings",
      "Showing no concern for others",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 83,
    question: "How can one improve adaptability?",
    options: [
      "Resisting change",
      "Being open to new experiences and challenges",
      "Avoiding learning new skills",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 84,
    question: "What is the role of feedback in professional growth?",
    options: [
      "Ignoring it",
      "Using it for self-improvement",
      "Taking it personally and reacting negatively",
    ],
    answer: 1,
    testcode: "softskills",
  },
  {
    id: 85,
    question: "What is one way to stay motivated at work?",
    options: [
      "Setting goals and tracking progress",
      "Waiting for motivation to come naturally",
      "Doing only what is required",
    ],
    answer: 0,
    testcode: "softskills",
  },
  {
    id: 86,
    question:
      "Which layer of the OSI model is responsible for end-to-end communication?",
    options: ["Transport Layer", "Network Layer", "Data Link Layer"],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 87,
    question: "What protocol is used to assign IP addresses dynamically?",
    options: ["DNS", "DHCP", "ARP"],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 88,
    question:
      "Which of the following is NOT a valid state in process lifecycle?",
    options: ["New", "Ready", "Execute"],
    answer: 2,
    testcode: "cs",
  },
  {
    id: 89,
    question: "Which protocol is used to securely browse websites (HTTPS)?",
    options: ["TLS", "FTP", "SMTP"],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 90,
    question:
      "In relational databases, what does the term 'cardinality' refer to?",
    options: [
      "The number of tuples in a table",
      "The number of attributes in a table",
      "The number of foreign keys in a table",
    ],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 91,
    question:
      "Which operating system uses message passing for inter-process communication?",
    options: ["UNIX", "Windows", "Microkernel-based OS"],
    answer: 2,
    testcode: "cs",
  },
  {
    id: 92,
    question:
      "Which layer in the OSI model deals with encryption and compression?",
    options: ["Presentation Layer", "Session Layer", "Transport Layer"],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 93,
    question: "Which of the following is a reliable transport protocol?",
    options: ["UDP", "TCP", "IP"],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 94,
    question: "Which address is used at the Data Link Layer?",
    options: ["MAC Address", "IP Address", "Port Number"],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 95,
    question: "Which layer ensures error-free delivery of data?",
    options: ["Session Layer", "Transport Layer", "Presentation Layer"],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 96,
    question: "What does DNS stand for?",
    options: [
      "Dynamic Number System",
      "Domain Name System",
      "Data Network Service",
    ],
    answer: 1,
    testcode: "cs-cn",
  },
  {
    id: 97,
    question: "Which device operates at the Network Layer?",
    options: ["Switch", "Router", "Hub"],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 98,
    question: "HTTP is a ____ protocol.",
    options: ["connection-oriented", "connectionless", "transport layer"],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 99,
    question: "Which protocol is used to retrieve emails from a server?",
    options: ["SMTP", "POP3", "HTTP"],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 100,
    question:
      "Which of the following IP classes provides the most number of hosts?",
    options: ["Class A", "Class B", "Class C"],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 101,
    question:
      "Which of the following protocols is used to assign IP addresses dynamically?",
    options: ["DNS", "DHCP", "ARP"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 102,
    question: "Which layer of the OSI model is responsible for routing?",
    options: ["Data Link", "Network", "Transport"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 103,
    question: "What does the acronym TTL stand for in networking?",
    options: ["Time To Leave", "Time To Live", "Transfer To Line"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 104,
    question: "Which of the following is a connection-oriented protocol?",
    options: ["UDP", "IP", "TCP"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 105,
    question: "Which device operates at the Data Link layer of the OSI model?",
    options: ["Switch", "Router", "Repeater"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 106,
    question: "In networking, what is the primary purpose of NAT?",
    options: [
      "To manage DNS",
      "To allow multiple devices to share a public IP",
      "To assign MAC addresses",
    ],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 107,
    question:
      "Which protocol is used to translate domain names into IP addresses?",
    options: ["ARP", "DNS", "FTP"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 108,
    question: "What is the default port number for HTTPS?",
    options: ["80", "21", "443"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 109,
    question:
      "What is the maximum length of a standard IPv4 address in decimal notation?",
    options: ["16 characters", "15 characters", "12 characters"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 110,
    question: "What kind of addressing is used in IPv6?",
    options: ["32-bit", "64-bit", "128-bit"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 111,
    question: "What is the main purpose of an operating system?",
    options: [
      "Compiling code",
      "Managing computer hardware and software resources",
      "Designing user interfaces",
    ],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 112,
    question: "Which scheduling algorithm gives minimum average waiting time?",
    options: ["FCFS", "SJF", "Round Robin"],
    answer: 1,
    testcode: "cs-os",
  },
  {
    id: 113,
    question: "What is a deadlock?",
    options: [
      "A process that is blocked forever",
      "A process that terminates prematurely",
      "A process in waiting state",
    ],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 114,
    question:
      "Which memory allocation technique suffers from external fragmentation?",
    options: ["Paging", "Segmentation", "Contiguous memory allocation"],
    answer: 2,
    testcode: "cs",
  },
  {
    id: 115,
    question: "What is the purpose of the fork() system call?",
    options: [
      "To create a new process",
      "To terminate a process",
      "To execute a new program",
    ],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 116,
    question: "Which of these is a non-preemptive scheduling algorithm?",
    options: [
      "Round Robin",
      "SJF (non-preemptive)",
      "Priority Scheduling (preemptive)",
    ],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 117,
    question: "What is a critical section?",
    options: [
      "A segment of code with a syntax error",
      "A segment of code that accesses shared resources",
      "A part of the kernel code",
    ],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 118,
    question:
      "Which one of the following is not a valid page replacement algorithm?",
    options: ["LRU", "FIFO", "LIFO"],
    answer: 2,
    testcode: "cs",
  },
  {
    id: 119,
    question: "What is thrashing?",
    options: [
      "Excessive CPU usage",
      "Excessive page faults",
      "Improper disk scheduling",
    ],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 120,
    question:
      "Which of the following uses the least amount of memory per process?",
    options: ["Multithreading", "Multiprocessing", "Time-sharing"],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 121,
    question: "What does ACID stand for in DBMS?",
    options: [
      "Atomicity, Consistency, Isolation, Durability",
      "Accuracy, Consistency, Integrity, Durability",
      "Atomicity, Concurrency, Integrity, Dependability",
    ],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 122,
    question: "Which SQL command is used to remove a table from the database?",
    options: ["DELETE", "REMOVE", "DROP"],
    answer: 2,
    testcode: "cs",
  },
  {
    id: 123,
    question: "What is the primary key?",
    options: [
      "A key that uniquely identifies a record",
      "A key that can be null",
      "A key used to create indexes",
    ],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 124,
    question: "Which of the following is a DML command?",
    options: ["CREATE", "INSERT", "DROP"],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 125,
    question: "Which normal form eliminates transitive dependency?",
    options: ["1NF", "2NF", "3NF"],
    answer: 2,
    testcode: "cs",
  },
  {
    id: 126,
    question: "Which join returns only the matching rows from both tables?",
    options: ["INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN"],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 127,
    question: "What is a foreign key?",
    options: [
      "A key that references the primary key of another table",
      "A unique key in the same table",
      "A candidate key not selected as primary",
    ],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 128,
    question: "Which indexing technique uses a tree structure?",
    options: ["Hash Indexing", "B+ Tree Indexing", "Clustered Indexing"],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 129,
    question: "Which of the following ensures referential integrity?",
    options: ["Foreign Key", "Primary Key", "Index"],
    answer: 0,
    testcode: "cs",
  },
  {
    id: 130,
    question:
      "Which of the following is not a feature of a relational database?",
    options: [
      "Tables with rows and columns",
      "Procedural data retrieval",
      "Support for SQL",
    ],
    answer: 1,
    testcode: "cs",
  },
  {
    id: 131,
    question: "What is the time complexity of binary search on a sorted array?",
    options: ["O(n)", "O(log n)", "O(n log n)"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 132,
    question: "Which of the following data structures uses LIFO order?",
    options: ["Queue", "Stack", "Heap"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 133,
    question: "Which keyword is used to define a function in Python?",
    options: ["function", "def", "func"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 134,
    question: "Which data structure is used in Breadth-First Search (BFS)?",
    options: ["Stack", "Queue", "Tree"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 135,
    question:
      "What will be the output of 3 + 2 * 2 in most programming languages?",
    options: ["10", "7", "9"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 136,
    question: "Which of the following is a mutable data type in Python?",
    options: ["Tuple", "String", "List"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 137,
    question: "What is the output of 'Hello' + str(5)?",
    options: ["Hello5", "Hello", "Error"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 138,
    question: "Which operator is used for exponentiation in Python?",
    options: ["^", "**", "%"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 139,
    question:
      "Which sorting algorithm has the best average-case time complexity?",
    options: ["Bubble Sort", "Quick Sort", "Selection Sort"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 140,
    question: "Which of these is not a valid loop structure in C?",
    options: ["for", "loop", "while"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 141,
    question: "Which of the following is not a primitive data type in Java?",
    options: ["int", "boolean", "String"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 142,
    question:
      "Which of the following is used to allocate memory dynamically in C?",
    options: ["malloc", "alloc", "assign"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 143,
    question: "What is the result of 7 % 3 in most languages?",
    options: ["1", "2", "3"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 144,
    question: "Which of the following is true for recursion?",
    options: [
      "Requires a base condition",
      "Always faster than iteration",
      "Cannot call itself",
    ],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 145,
    question:
      "Which language is most commonly used for system-level programming?",
    options: ["JavaScript", "C", "Python"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 146,
    question: "What does the 'continue' statement do in a loop?",
    options: ["Stops the loop", "Skips current iteration", "Exits program"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 147,
    question:
      "Which of the following is not a feature of object-oriented programming?",
    options: ["Encapsulation", "Polymorphism", "Compilation"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 148,
    question: "Which of these is not a valid identifier in C?",
    options: ["_var", "3var", "var_3"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 149,
    question: "Which keyword is used to create a class in Java?",
    options: ["class", "Class", "define"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 150,
    question:
      "Which algorithm is best suited for finding the shortest path in a weighted graph?",
    options: ["DFS", "BFS", "Dijkstra's Algorithm"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 151,
    question: "What will be the output of 10 >> 1 in C?",
    options: ["5", "20", "0"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 152,
    question:
      "Which of the following data structures is used for implementing recursion?",
    options: ["Queue", "Stack", "Array"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 153,
    question: "Which of the following is used to define an interface in Java?",
    options: ["class", "interface", "implements"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 154,
    question: "Which keyword is used in C++ to inherit a class?",
    options: ["extends", "inherits", "public"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 155,
    question: "Which of the following is not an O(n log n) algorithm?",
    options: ["Merge Sort", "Heap Sort", "Bubble Sort"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 156,
    question: "What is the output of print(type([])) in Python?",
    options: ["<class 'list'>", "<type 'list'>", "list"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 157,
    question:
      "Which operator is used for logical AND in most programming languages?",
    options: ["&&", "||", "&"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 158,
    question:
      "What is the time complexity of inserting at the end in an array?",
    options: ["O(1)", "O(n)", "O(log n)"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 159,
    question: "Which language is primarily used for front-end web development?",
    options: ["Python", "JavaScript", "C++"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 160,
    question: "Which algorithm uses a divide and conquer strategy?",
    options: ["Merge Sort", "Bubble Sort", "Linear Search"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 161,
    question:
      'What is the output of the following code?\n\nint a = 5;\nint b = a++;\nprintf("%d %d", a, b);',
    options: ["5 5", "6 5", "6 6"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 162,
    question: "Which of the following sorting algorithms is stable?",
    options: ["Quick Sort", "Heap Sort", "Merge Sort"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 163,
    question:
      "What is the time complexity of inserting an element into a Binary Search Tree (average case)?",
    options: ["O(log n)", "O(n)", "O(1)"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 164,
    question: "Which bitwise operator is used to check if a number is even?",
    options: ["&", "|", "^"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 165,
    question: "Which of the following problems is best solved using a stack?",
    options: [
      "Level-order traversal",
      "Infix to postfix conversion",
      "Finding shortest path",
    ],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 166,
    question:
      "Which of the following will you use to find the middle element of a linked list in one pass?",
    options: ["Two-pointer approach", "Recursion", "Stack"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 167,
    question:
      'What is the output of this Java code?\n\nSystem.out.println("5" + 2 + 3);',
    options: ["55", "523", "8"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 168,
    question: "Which data structure is used to implement recursion internally?",
    options: ["Heap", "Stack", "Queue"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 169,
    question: "Which of the following is true for HashMap in Java?",
    options: [
      "Allows duplicate keys",
      "Allows one null key",
      "Is synchronized",
    ],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 170,
    question: "What is the best-case time complexity of quicksort?",
    options: ["O(n log n)", "O(n)", "O(n^2)"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 171,
    question: "Which traversal of binary tree gives sorted output for BST?",
    options: ["Preorder", "Inorder", "Postorder"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 172,
    question:
      "You are given an array. What technique would you use to detect duplicates efficiently?",
    options: ["Sorting", "Hashing", "Two Pointers"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 173,
    question: "Which algorithm is used in the KMP string matching algorithm?",
    options: ["Prefix Table", "Suffix Tree", "Sliding Window"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 174,
    question:
      "Which of the following code snippets finds the factorial recursively in C?",
    options: [
      "int fact(int n) { return n * fact(n - 1); }",
      "int fact(int n) { if(n==0) return 1; return n * fact(n - 1); }",
      "int fact(int n) { return n + fact(n - 1); }",
    ],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 175,
    question:
      'What is the output of the following code?\n\nint x = 10;\nprintf("%d", x == 10 ? 1 : 0);',
    options: ["10", "1", "0"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 176,
    question:
      "Which of the following algorithms is used for cycle detection in a graph?",
    options: ["DFS", "Dijkstra", "Prim's"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 177,
    question:
      "Which C++ container allows constant time insertion and deletion at both ends?",
    options: ["vector", "list", "deque"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 178,
    question:
      "Which is the most efficient data structure for implementing a priority queue?",
    options: ["Array", "Stack", "Heap"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 179,
    question:
      "Which of the following statements is true about a static method in Java?",
    options: [
      "Can access instance variables directly",
      "Cannot be called without creating an object",
      "Can be called using the class name",
    ],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 180,
    question:
      "Which of the following time complexities is better for large input sizes?",
    options: ["O(n^2)", "O(n log n)", "O(n^3)"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 181,
    question: "Which data structure uses LIFO (Last In First Out) principle?",
    options: ["Queue", "Stack", "Array"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 182,
    question:
      "Which of the following is not a characteristic of an object-oriented language?",
    options: ["Encapsulation", "Polymorphism", "Top-down design"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 183,
    question: "What will be the result of 10 / 3 in most C/C++ compilers?",
    options: ["3", "3.33", "Depends on compiler"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 184,
    question: "Which keyword is used to prevent method overriding in Java?",
    options: ["final", "static", "private"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 185,
    question:
      "Which of the following searching algorithms is best for a sorted array?",
    options: ["Linear Search", "Binary Search", "Hashing"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 186,
    question: "In which case does a queue throw 'Underflow'?",
    options: ["When it is full", "When it is empty", "When front == rear"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 187,
    question: "What is the space complexity of Merge Sort?",
    options: ["O(1)", "O(log n)", "O(n)"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 188,
    question: "Which of the following is not true about arrays?",
    options: ["Fixed size", "Random access", "Automatically resizes"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 189,
    question: "Which of the following is a valid identifier in C?",
    options: ["int", "1var", "_count"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 190,
    question: "Which of these is not a loop structure in Java?",
    options: ["for", "repeat", "while"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 191,
    question:
      "Which operator is used to access members of a structure using a pointer?",
    options: [".", "->", "&"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 192,
    question:
      "Which method is used to insert an element at the end of a vector in C++?",
    options: ["add()", "push()", "push_back()"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 193,
    question: "Which data structure is used in Breadth-First Search (BFS)?",
    options: ["Stack", "Queue", "HashMap"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 194,
    question: "Which of the following is not a type of tree traversal?",
    options: ["Inorder", "Outorder", "Postorder"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 195,
    question: "What is the return type of strcmp() in C?",
    options: ["char", "int", "bool"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 196,
    question: "Which of these languages is compiled?",
    options: ["Python", "Java", "C"],
    answer: 2,
    testcode: "programming",
  },
  {
    id: 197,
    question: "Which of the following is true about recursion?",
    options: [
      "Must have a base case",
      "Always faster than iteration",
      "Uses queue internally",
    ],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 198,
    question: "What is the default initial value of a local variable in C?",
    options: ["0", "Garbage value", "NULL"],
    answer: 1,
    testcode: "programming",
  },
  {
    id: 199,
    question:
      'What is the output of this code?\n\nint a = 5;\nprintf("%d", a == 5 && 10 > 3);',
    options: ["1", "0", "True"],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 200,
    question: "Which of the following is true for tail recursion?",
    options: [
      "Recursive call is the last statement",
      "Uses more stack",
      "Reduces performance",
    ],
    answer: 0,
    testcode: "programming",
  },
  {
    id: 201,
    question: "Which scheduling algorithm may lead to starvation?",
    options: ["Round Robin", "FCFS", "Shortest Job Next"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 202,
    question: "What is a critical section in OS?",
    options: [
      "A part of memory used by kernel",
      "Code that accesses shared resources",
      "An infinite loop in user process",
    ],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 203,
    question:
      "Which of the following is a non-preemptive scheduling algorithm?",
    options: ["Round Robin", "FCFS", "SRTF"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 204,
    question:
      "Which of the following is NOT a valid page replacement algorithm?",
    options: ["FIFO", "LRU", "SJF"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 205,
    question: "What does thrashing mean in an operating system?",
    options: ["Excessive CPU usage", "Frequent page faults", "Disk failure"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 206,
    question: "Which system call is used to create a new process?",
    options: ["exec()", "fork()", "exit()"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 207,
    question: "Which of the following is used for inter-process communication?",
    options: ["Semaphore", "Mutex", "Pipe"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 208,
    question: "What is the purpose of a semaphore?",
    options: [
      "To schedule threads",
      "To manage memory",
      "To prevent race conditions",
    ],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 209,
    question: "Which of the following is NOT a deadlock condition?",
    options: ["Mutual exclusion", "Preemption", "Circular wait"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 210,
    question: "Which OS component is responsible for memory allocation?",
    options: ["Shell", "Loader", "Memory Manager"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 211,
    question:
      "Which algorithm is used in operating systems for page replacement?",
    options: ["Dijkstra", "LRU", "Kruskal"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 212,
    question: "What is the primary goal of time-sharing OS?",
    options: ["Security", "Batch processing", "Fast response to all users"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 213,
    question: "What is a context switch?",
    options: [
      "Switching from one OS to another",
      "Switching between user and kernel mode",
      "Switching CPU from one process to another",
    ],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 214,
    question:
      "Which memory management scheme suffers from external fragmentation?",
    options: ["Paging", "Segmentation", "Contiguous allocation"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 215,
    question: "Which of the following is used to keep track of memory usage?",
    options: ["Page table", "Bitmap", "Process table"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 216,
    question: "What is the role of dispatcher in OS?",
    options: ["Assign memory", "Switch process context", "Schedule I/O"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 217,
    question: "Which system program loads the operating system into memory?",
    options: ["Compiler", "Loader", "Bootstrap"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 218,
    question: "What is demand paging?",
    options: [
      "Loading all pages at once",
      "Loading pages only when needed",
      "Replacing pages randomly",
    ],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 219,
    question: "Which of these is NOT an attribute of a process?",
    options: ["Process ID", "Program Counter", "RAM Frequency"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 220,
    question: "Which technique is used to prevent deadlock?",
    options: ["Circular wait", "Resource preemption", "Banker's algorithm"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 221,
    question: "Which SQL statement is used to extract data from a database?",
    options: ["GET", "SELECT", "EXTRACT"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 222,
    question: "What does the WHERE clause do in SQL?",
    options: ["Specifies the columns", "Filters records", "Joins tables"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 223,
    question:
      "Which of the following is used to remove duplicate records in SQL?",
    options: ["UNIQUE", "DISTINCT", "REMOVE"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 224,
    question: "What is the purpose of the GROUP BY clause in SQL?",
    options: ["To sort data", "To filter data", "To aggregate data"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 225,
    question:
      "Which of the following is used to combine rows from two or more tables?",
    options: ["JOIN", "MERGE", "APPEND"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 226,
    question: "Which SQL function returns the number of rows?",
    options: ["COUNT()", "SUM()", "ROWNUM()"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 227,
    question: "How do you rename a column in the result set?",
    options: ["AS", "RENAME", "CHANGE"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 228,
    question: "Which operator is used for pattern matching in SQL?",
    options: ["LIKE", "MATCHES", "FIND"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 229,
    question: "What does the HAVING clause do in SQL?",
    options: ["Filters groups", "Filters rows", "Joins tables"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 230,
    question: "What will the result of SELECT COUNT(*) FROM table; return?",
    options: ["Number of columns", "Number of rows", "Total size of table"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 231,
    question: "Which join returns only matching rows from both tables?",
    options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 232,
    question: "Which clause is used to sort the result set in SQL?",
    options: ["ORDER BY", "GROUP BY", "SORT BY"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 233,
    question: "What keyword is used to remove a table from the database?",
    options: ["REMOVE", "DELETE", "DROP"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 234,
    question: "Which of the following is a valid SQL data type?",
    options: ["INTEGER", "ALPHANUM", "STRING"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 235,
    question: "What does NULL represent in a database?",
    options: ["0", "Empty string", "Unknown value"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 236,
    question: "Which of the following is used to update data in SQL?",
    options: ["CHANGE", "MODIFY", "UPDATE"],
    answer: 2,
    testcode: "cn",
  },
  {
    id: 237,
    question: "What is the default sorting order of ORDER BY clause?",
    options: ["DESC", "ASC", "NONE"],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 238,
    question: "Which clause is used to limit the number of rows returned?",
    options: ["LIMIT", "ROWNUM", "TOP"],
    answer: 0,
    testcode: "cn",
  },
  {
    id: 239,
    question: "What is the purpose of a foreign key?",
    options: [
      "To uniquely identify a record",
      "To reference a record in another table",
      "To encrypt data",
    ],
    answer: 1,
    testcode: "cn",
  },
  {
    id: 240,
    question: "Which of the following SQL statements is used to insert data?",
    options: ["ADD INTO", "PUT", "INSERT INTO"],
    answer: 2,
    testcode: "cn",
  },
];
